src/main/java/infobalt/robusta/ui/controllers/MemberController.java
package infobalt.robusta.ui.controllers;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;

import org.primefaces.context.RequestContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.security.crypto.password.PasswordEncoder;

import infobalt.robusta.entities.Member;
import infobalt.robusta.entities.Member.MemberStatus;
import infobalt.robusta.model.MemberModel;
import infobalt.robusta.model.RequestModel;
import infobalt.robusta.service.MemberService;

public class MemberController {

	private static final Logger logger = LoggerFactory.getLogger(MemberController.class);

	private MemberModel model;

	private MemberService memberService;

	private RequestModel requestModel;

	private PasswordEncoder passwordEncoder;


	public void create() {
		model.setMember(new Member());
	}

	public void update(Member member) {
		model.setMember(member);
	}

	public void changePassword(Member member) {
		model.setMember(member);
	}

	public List<Member> loadMembers() {
		return memberService.findAllMembers();
	}

	public void cancel() {
		model.setMember(null);
	}

	public MemberStatus[] getMemberStatuses() {
		return MemberStatus.values();
	}

	/**
	 * Saves or updates certain user with all set parameters, such as name,
	 * password and other input data
	 */
	public void save() {
		Member member = model.getMember();

		if (!requestModel.getNewPassword().isEmpty()) {
			logger.debug("Password list is not empty");

			member.setPassword(requestModel.getNewPassword());
			logger.debug("User(ID{}) was set with password from the list", member.getId());

			member.setPassword(passwordEncoder.encode(member.getPassword()));
			logger.debug("User's(ID{}) password encoded", member.getId());
		}

		memberService.createMember(member);
		cancel();
		RequestContext rc = RequestContext.getCurrentInstance();
		rc.execute("PF('createMember').hide()");
	}

	public void delete(Member member) {
		memberService.deleteMember(member);
	}

	/**
	 * Set status DISABLED to a certain user, so that user can not login to the
	 * system
	 * 
	 * @param member
	 */
	public void disable(Member member) {
		member.setStatus(MemberStatus.DISABLED);
		logger.debug("User(ID{}) was disabled", member.getId());
		memberService.createMember(member);
		cancel();
	}
	
	/**
	 * Set status ACTIVE to a certain user, so that user can not login to the
	 * system
	 * 
	 * @param member
	 */
	public void activate(Member member) {
		member.setStatus(MemberStatus.ACTIVE);
		logger.debug("User(ID{}) was activated", member.getId());
		memberService.createMember(member);
		cancel();
	}


	/**
	 * Since email is used as a login name, it has to be unique. Method checks
	 * if the input email is unique or already exist in the database.
	 * 
	 * @param context
	 * @param component
	 * @param value
	 * @throws ValidatorException
	 *             if the input email is found in the database, so it is not
	 *             unique.
	 */
	public void validateUniqueEmail(FacesContext context, UIComponent component, Object value)
			throws ValidatorException {

		String data = value.toString();

		for (Member member : memberService.findAllMembers()) {
			if (member.getLoginName().equalsIgnoreCase(data)) {
				logger.debug("User(ID{}) email is not ignored", member.getId());
				if (!(model.getMember().getId() == 0) || (model.getMember().getId() == member.getId())) {
					logger.debug("User(ID{}) email is not zero and is unique", member.getId());
					return;
				} else {
					FacesMessage message = new FacesMessage("A user with this email already exists");
					message.setSeverity(FacesMessage.SEVERITY_ERROR);
					logger.error("User(ID{}) email is not unique", member.getId());
					throw new ValidatorException(message);
				}
			}
		}
	}

	/**
	 * Since password is a mandatory field it can't be empty. Method checks if
	 * input field is filed with a value.
	 * 
	 * @param context
	 * @param component
	 * @param value
	 * @throws ValidatorException
	 *             if input field is empty and password is not entered
	 */
	public void validateNewPassword(FacesContext context, UIComponent component, Object value)
			throws ValidatorException {

		if (value.toString().isEmpty() && (model.getMember().getId() == null)) {
			FacesMessage message = new FacesMessage("A new user must have a password");
			message.setSeverity(FacesMessage.SEVERITY_ERROR);
			logger.error("Password for user(ID{}) is not entered", model.getMember().getId());
			throw new ValidatorException(message);
		}
	}
	
	public void setPasswordEncoder(PasswordEncoder passwordEncoder) {
		this.passwordEncoder = passwordEncoder;
	}

	public RequestModel getProjectController2() {
		return requestModel;
	}

	public void setProjectController2(RequestModel requestModel) {
		this.requestModel = requestModel;
	}

	public MemberModel getModel() {
		return model;
	}

	public void setModel(MemberModel model) {
		this.model = model;
	}

	public MemberService getMemberService() {
		return memberService;
	}

	public void setMemberService(MemberService memberService) {
		this.memberService = memberService;
	}

}

src/main/webapp/pages/secure/admin/AdminMenu.xhtml
<!DOCTYPE html>
<h:html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head></h:head>
<h:body>

	<ui:composition>


		<h:form>
			<p:tabMenu activeIndex="#{param.i}">
				<p:menuitem value="Members management"
					outcome="/pages/secure/admin/membersList" icon="ui-icon-search">
					<f:param name="i" value="0" />
				</p:menuitem>
				<p:menuitem value="Projects management "
					outcome="/pages/secure/admin/projectsList" icon="ui-icon-wrench">
					<f:param name="i" value="1" />
				</p:menuitem>
				<p:menuitem value="Comments management "
					outcome="/pages/secure/admin/commentsList" icon="ui-icon-wrench">
					<f:param name="i" value="2" />
				</p:menuitem>
				<p:menuitem id="help" value="Help" outcome="/pages/secure/admin/help">
					<f:param name="i" value="3" />
				</p:menuitem>
				<p:menuitem style="float:right!important;" value="Logout"
					id="logout" icon="fa fa-sign-out" action="#{loginMgmtBean.logout}"></p:menuitem>
			</p:tabMenu>
		</h:form>


	</ui:composition>
</h:body>
</h:html>

src/main/webapp/pages/secure/admin/AdminTemplate.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title><ui:insert name="title">
  		No title
  	</ui:insert></title>
	<h:outputStylesheet id="stylesheet" name="style.css" />
</h:head>
<h:body>
	<div id="header">
		<ui:include src="../header.xhtml" />
	</div>
	<div id="container">
		<div id="menu">
			<ui:include src="AdminMenu.xhtml" />
		</div>
		<div id="contents">
			<ui:insert name="content">
		  		No content
		  	</ui:insert>
			<br /> <br />
		</div>

		<h:form>
			<p:commandButton value="Logout" id="logout"
				action="#{loginMgmtBean.logout}" />
		</h:form>

		<div id="footer">
			<ui:include src="../footer.xhtml" />
		</div>
	</div>
</h:body>
</html>

src/main/webapp/pages/secure/admin/commentsList.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="AdminTemplate.xhtml">

	<ui:define name="title">
 	 	All Comments
 	 </ui:define>

	<ui:define name="content">

		<h1>All comments:</h1>

		<h:panelGroup layout="block" id="lazyCommentsDiv">
			<h:form id="lazyComments">
				<p:dataTable var="comment" widgetVar="lazyCommentTable"
					value="#{lazyCommentsModel}" paginator="true" rows="10"
					paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
					rowsPerPageTemplate="5,10,15" id="commentsTable" lazy="true"
					paginatorPosition="bottom">

					<p:column headerText="Id" sortBy="#{comment.id}"
						filterBy="#{comment.id}">
						<h:outputText value="#{comment.id}" />
					</p:column>

					<p:column headerText="Author"
						sortBy="#{comment.author.getFullName()}"
						filterBy="#{comment.author.getFullName()}">
						<h:outputText value="#{comment.author.getFullName()}" />
					</p:column>

					<p:column headerText="Comment Date" sortBy="#{comment.commentDate}"
						filterBy="#{comment.commentDate}">
						<f:facet name="filter">
							<h:inputHidden id="commentDate" />
						</f:facet>
						<f:facet name="header">
							<p:outputLabel value="Created date" />
							<br />
							<p:calendar id="from" pattern="yyyy-MM-dd"
								placeholder="From date">
								<p:ajax event="valueChange"
									onstart="$(PrimeFaces.escapeClientId('#{p:component('commentDate')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from')}_input'))[0].value + '-' + $(PrimeFaces.escapeClientId('#{p:component('to')}_input'))[0].value"
									oncomplete="PF('lazyCommentTable').filter()" />
								<p:ajax event="dateSelect"
									onstart="$(PrimeFaces.escapeClientId('#{p:component('commentDate')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from')}_input'))[0].value + '-' + $(PrimeFaces.escapeClientId('#{p:component('to')}_input'))[0].value"
									oncomplete="PF('lazyCommentTable').filter()" />
							</p:calendar>
							<p:calendar id="to" pattern="yyyy-MM-dd" placeholder="To date">
								<p:ajax event="valueChange"
									onstart="$(PrimeFaces.escapeClientId('#{p:component('commentDate')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from')}_input'))[0].value + '-' + $(PrimeFaces.escapeClientId('#{p:component('to')}_input'))[0].value"
									oncomplete="PF('lazyCommentTable').filter()" />
								<p:ajax event="dateSelect"
									onstart="$(PrimeFaces.escapeClientId('#{p:component('commentDate')}'))[0].value = $(PrimeFaces.escapeClientId('#{p:component('from')}_input'))[0].value + '-' + $(PrimeFaces.escapeClientId('#{p:component('to')}_input'))[0].value"
									oncomplete="PF('lazyCommentTable').filter()" />
							</p:calendar>
						</f:facet>
						<h:outputText value="#{comment.commentDate}">
						</h:outputText>
					</p:column>

					<p:column id="colText" filterStyleClass="commentFilter"
						headerText="Comment Text" colspan="3"
						sortBy="#{comment.commentText}" filterBy="#{comment.commentText}">
						<h:outputText value="#{comment.commentText}" />
					</p:column>

					<p:column headerText="Action">
						<p:commandButton value="Delete"
							action="#{commentController.delete(comment)}" update="@form">
							<p:confirm header="Delete"
								message="Are you sure you want to delete this entry?"
								icon="ui-icon-alert" />
						</p:commandButton>
					</p:column>
				</p:dataTable>

				<p:confirmDialog global="true">
					<p:commandButton value="Yes" type="button"
						styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
					<p:commandButton value="No" type="button"
						styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
				</p:confirmDialog>
			</h:form>
		</h:panelGroup>
	</ui:define>


</ui:composition>

src/main/webapp/pages/secure/admin/help.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="AdminTemplate.xhtml">

	<ui:define name="title">
 	 	HELP
 	 </ui:define>

	<ui:define name="content">
		
		<h1>Help</h1>
		
		<h:outputLink target="_blank" value="/robusta/resources/RobustaUserManual.pdf">Robusta Manual for basic tasks</h:outputLink>
		
		

	</ui:define>

</ui:composition>

src/main/webapp/pages/secure/admin/membersList.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="AdminTemplate.xhtml">

	<ui:define name="title">
 	 	Team Members
 	 </ui:define>

	<ui:define name="content">

		<h1>All members</h1>
		<h:form id="dataTable">

			<p:dataTable value="#{memberController.loadMembers()}" var="member"
				styleClass="truncate">
				<p:column headerText="Id">
					<h:outputText value="#{member.id}" />
				</p:column>

				<p:column headerText="Name">
					<h:outputText value="#{member.name}" />
				</p:column>

				<p:column headerText="Last name">
					<h:outputText value="#{member.surname}" />
				</p:column>

				<p:column headerText="Login/Email">
					<h:outputText value="#{member.loginName}" />
				</p:column>

				<p:column headerText="Registration Date">
					<h:outputText value="#{member.registrationDate}" />
				</p:column>
				<p:column headerText="Member Status">
					<h:outputText value="#{member.status.label}" />
				</p:column>

				<p:column>
					<p:commandButton value="Disable" rendered="#{member.status ne 'DISABLED'}"
						action="#{memberController.disable(member)}" update="@form">
						<p:confirm header="Disable"
							message="Are you sure you want to disable this user?" />
					</p:commandButton>
					<p:commandButton value="Activate" rendered="#{member.status ne 'ACTIVE'}"
						action="#{memberController.activate(member)}" update="@form">
					</p:commandButton>
					</p:column>
					<p:column>
					<p:commandButton value="Edit"
						action="#{memberController.update(member)}"
						update="dataTable updateForm"
						oncomplete="PF('createMember').show();" />
				</p:column>
			</p:dataTable>
		</h:form>


		<p:commandButton action="#{memberController.create}"
			update="updateForm" value=" Create"
			oncomplete="PF('createMember').show();" />


		<p:defaultCommand target="dummy" />
		<p:commandButton id="dummy" process="@none" global="false"
			style="display:none;" />

		<p:confirmDialog global="true">
			<p:commandButton value="Yes" type="button"
				styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
			<p:commandButton value="No" type="button"
				styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
		</p:confirmDialog>

		<p:dialog header="Create/Edit Member" widgetVar="createMember"
			modal="true" showEffect="blind" hideEffect="explode"
			resizable="false">
			<h:form id="updateForm">
				<p:outputPanel rendered="#{memberModel.member != null}">
					<h:panelGrid columns="3" cellpadding="5">
						<p:outputLabel for="name">Name:</p:outputLabel>
						<p:inputText id="name"
							value="#{memberController.model.member.name}"></p:inputText>
						<p:message for="name"></p:message>

						<p:outputLabel for="surname">Last name:</p:outputLabel>
						<p:inputText id="surname"
							value="#{memberController.model.member.surname}"></p:inputText>
						<p:message for="surname"></p:message>

						<p:outputLabel for="login">Email/Login:</p:outputLabel>
						<p:inputText id="login"
							validator="#{memberController.validateUniqueEmail}"
							value="#{memberController.model.member.loginName}"
							required="true" requiredMessage="A valid email must be present"></p:inputText>
						<p:message for="login"></p:message>

						<p:outputLabel for="password">Password:</p:outputLabel>
						<p:inputText id="password"
							validator="#{memberController.validateNewPassword}"
							value="#{memberController.projectController2.newPassword}"></p:inputText>
						<p:message for="password"></p:message>

						<p:outputLabel for="status">Member status:</p:outputLabel>
						<p:selectOneMenu value="#{memberController.model.member.status}"
							id="status">
							<f:selectItems value="#{memberController.memberStatuses}"
								var="status" itemValue="#{status}" itemLabel="#{status.label}" />
						</p:selectOneMenu>
						<p />
						<p:commandButton value="Save"
							actionListener="#{memberController.save}"
							update="updateForm dataTable">
						</p:commandButton>
						<p:commandButton value="Cancel"
							actionListener="#{memberController.cancel}"
							update="updateForm dataTable"
							oncomplete="PF('createMember').hide();" immediate="true"></p:commandButton>
					</h:panelGrid>
				</p:outputPanel>
			</h:form>
		</p:dialog>
	</ui:define>
</ui:composition>

src/main/webapp/pages/secure/admin/projectsList.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="AdminTemplate.xhtml">

	<ui:define name="title">
 	 	Projects
 	 </ui:define>

	<ui:define name="content">

		<h1>All Projects:</h1>

		<h:form id="dataTable">

			<p:dataTable value="#{projectController.loadProjects()}"
				var="project">
				<p:column headerText="Id">
					<h:outputText value="#{project.id}" />
				</p:column>

				<p:column headerText="Created">
					<h:outputText value="#{project.dateCreated}">
						<f:convertDateTime pattern="yyyy-MM-dd" />
					</h:outputText>
				</p:column>

				<p:column headerText="Title">
					<h:outputText value="#{project.name}" />
				</p:column>

				<p:column headerText="Start">
					<h:outputText value="#{project.startDate}" />
				</p:column>

				<p:column headerText="End Date">
					<h:outputText value="#{project.endDate}" />
				</p:column>

				<p:column headerText="Summary">
					<h:outputText value="#{project.description}" />
				</p:column>

				<p:column headerText="Project Manager">
					<h:outputText value="#{project.projectManager.getFullName()}" />
				</p:column>

				<p:calendar id="project_enddate"
					value="#{projectController.projectModel.project.endDate}"
					pattern="yyyy-MM-dd">
					<f:validator binding="#{projectDatesValidator}" />
					<f:attribute name="projectStartDateComponent"
						value="#{projectStartDateComponent}" />
				</p:calendar>
				<p:column headerText="Action">
					<p:commandButton value="Edit"
						action="#{projectController.updateProject(project)}"
						update="dataTable updateForm"
						oncomplete="PF('createProject').show();" />
				</p:column>
			</p:dataTable>
		</h:form>

		<p:commandButton action="#{projectController.createProject()}"
			update="updateForm" value=" Create"
			oncomplete="PF('createProject').show();" />




		<p:defaultCommand target="dummy" />
		<p:commandButton id="dummy" process="@none" global="false"
			style="display:none;" />

		<p:dialog header="Create/Edit Project" widgetVar="createProject"
			modal="true" showEffect="blind" hideEffect="explode"
			resizable="false">
			<h:form id="updateForm">
				<p:outputPanel rendered="#{projectModel.project != null}">
					<p:panelGrid columns="3" cellpadding="5">
						<p:outputLabel for="name">Title:</p:outputLabel>
						<p:inputText required="true"
							requiredMessage="Project must have a title" id="name"
							value="#{projectController.projectModel.project.name}"
							validator="#{projectController.validateUniqueProjectName}"></p:inputText>
						<p:message for="name"></p:message>
						<p:outputLabel for="project_startdate" value="Start date"></p:outputLabel>
						<p:calendar id="project_startdate" required="true"
							requiredMessage="Project must have a start date"
							binding="#{projectStartDateComponent}"
							value="#{projectController.projectModel.project.startDate}"
							pattern="yyyy-MM-dd"></p:calendar>
						<p:message for="project_startdate" />
						<p:outputLabel for="description" maxlength="250">Short description:</p:outputLabel>
						<p:inputTextarea id="description"
							value="#{projectController.projectModel.project.description}"></p:inputTextarea>
						<p:message for="description"></p:message>
						<p:outputLabel for="manager">Project Manager:</p:outputLabel>
						<p:selectOneMenu
							value="#{projectController.projectModel.managerId}" id="manager">
							<f:selectItem itemValue="#{null}" itemLabel="Not assigned"
								noSelectionOption="true"></f:selectItem>
							<f:selectItems value="#{projectController.getMembers()}"
								var="member" itemValue="#{member.id}"
								itemLabel="#{member.getFullName()}" />
						</p:selectOneMenu>
						<p:message for="manager"></p:message>
						<p:outputLabel for="project_enddate" value="End date"></p:outputLabel>
						<p:calendar id="project_enddate"
							value="#{projectController.projectModel.project.endDate}"
							pattern="yyyy-MM-dd">
							<f:validator binding="#{projectDatesValidator}" />
							<f:attribute name="projectStartDateComponent"
								value="#{projectStartDateComponent}" />
						</p:calendar>
						<p:message for="project_enddate" />
						<p:commandButton value="Save"
							actionListener="#{projectController.saveProject}"
							update="updateForm dataTable"></p:commandButton>
						<p:commandButton value="Cancel"
							actionListener="#{projectController.cancelProject}"
							update="updateForm dataTable"
							oncomplete="PF('createProject').hide();" immediate="true"></p:commandButton>
					</p:panelGrid>
					<p:tooltip id="toolTipDescription" for="description"
						trackMouse="true" value="Description cannot exceed 250 characters" />
				</p:outputPanel>

			</h:form>
		</p:dialog>
	</ui:define>
</ui:composition>