src/main/java/infobalt/robusta/entities/Assignment.java
package infobalt.robusta.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Assignment implements Serializable {

	private static final long serialVersionUID = -8401457450083000994L;

	public enum AssignmentStatus {
		TODO("To Do"), INPROGRESS("In Progress"), DONE("Done");

		private final String label;

		private AssignmentStatus(String label) {
			this.label = label;
		}

		public String getLabel() {
			return this.label;
		}
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@Column
	private String name;

	@Temporal(TemporalType.TIMESTAMP)
	private Date doneDate;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "done_author_id")
	private Member doneAuthor;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id")
	private Project project;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "creator_id")
	private Member creator;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "sprint_id")
	private Sprint sprint;

	@Column
	private String description;

	@Column
	private int valueInStoryPoints;

	@Column
	private AssignmentStatus status;

	@Temporal(TemporalType.TIMESTAMP)
	private Date creationDate;

	@Temporal(TemporalType.TIMESTAMP)
	private Date editedDate;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "member_id")
	private Member assignee;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Project getProject() {
		return project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public Member getCreator() {
		return creator;
	}

	public void setCreator(Member creator) {
		this.creator = creator;
	}

	public Sprint getSprint() {
		return sprint;
	}

	public void setSprint(Sprint sprint) {
		this.sprint = sprint;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getValueInStoryPoints() {
		return valueInStoryPoints;
	}

	public void setValueInStoryPoints(int valueInStoryPoints) {
		this.valueInStoryPoints = valueInStoryPoints;
	}

	public AssignmentStatus getStatus() {
		return status;
	}

	public void setStatus(AssignmentStatus status) {
		this.status = status;
	}

	public Date getCreationDate() {
		return creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public Date getEditedDate() {
		return editedDate;
	}

	public void setEditedDate(Date editedDate) {
		this.editedDate = editedDate;
	}

	public Member getAssignee() {
		return assignee;
	}

	public void setAssignee(Member assignee) {
		this.assignee = assignee;
	}

	public Member getDoneAuthor() {
		return doneAuthor;
	}

	public Date getDoneDate() {
		return doneDate;
	}

	public void setDoneAuthor(Member doneAuthor) {
		this.doneAuthor = doneAuthor;
	}

	public void setDoneDate(Date doneDate) {
		this.doneDate = doneDate;
	}

	@Override
	public String toString() {
		return ("assignment id: " + id + " name: " + name);
	}

}

src/main/java/infobalt/robusta/entities/Member.java
package infobalt.robusta.entities;

import java.io.Serializable;
import java.sql.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

@Entity
public class Member implements Serializable {

	private static final long serialVersionUID = -6704975159178904497L;

	public enum MemberStatus {
		ACTIVE("Active"), DISABLED("Disabled");

		private final String label;

		private MemberStatus(String label) {
			this.label = label;
		}

		public String getLabel() {
			return this.label;
		}
	}

	public Member() {
	}

	public Member(String loginName, String password) {
		this.loginName = loginName;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	private String name;
	private String surname;

	@NotNull
	private Date registrationDate;

	@Column(unique = true)
	@Pattern(regexp = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$", message = "This does not appear to be a valid email address")
	private String loginName;

	@NotNull
	@Size(max = 80)
	private String password;

	@Column(length = 20)
	@NotNull
	private String role = "user";

	@Enumerated(EnumType.STRING)
	private MemberStatus status;

	@ManyToMany(mappedBy = "workers", fetch = FetchType.LAZY)
	private List<Project> workingProjects;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getFullName() {
		if (this.name.isEmpty() && this.surname.isEmpty()) {
			return this.loginName;
		}
		return this.name + " " + this.surname;
	}

	public Date getRegistrationDate() {
		return registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	public MemberStatus getStatus() {
		return status;
	}

	public void setStatus(MemberStatus status) {
		this.status = status;
	}

	public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Override
	public String toString() {
		return "Member [id=" + id + ", name=" + name + ", surname=" + surname + ", registrationDate=" + registrationDate
				+ ", loginName=" + loginName + ", password=" + password + ", role=" + role + ", status=" + status;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((loginName == null) ? 0 : loginName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Member other = (Member) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (loginName == null) {
			if (other.loginName != null)
				return false;
		} else if (!loginName.equals(other.loginName))
			return false;
		return true;
	}

}

src/main/java/infobalt/robusta/ui/controllers/AssignmentController.java
package infobalt.robusta.ui.controllers;

import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import javax.faces.application.ConfigurableNavigationHandler;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;

import org.primefaces.event.SelectEvent;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import infobalt.robusta.entities.Assignment;
import infobalt.robusta.entities.Assignment.AssignmentStatus;
import infobalt.robusta.entities.Member;
import infobalt.robusta.entities.Member.MemberStatus;
import infobalt.robusta.entities.Project;
import infobalt.robusta.entities.Sprint;
import infobalt.robusta.model.AssignmentModel;
import infobalt.robusta.model.AssignmentSearchCriterias;
import infobalt.robusta.model.MemberModel;
import infobalt.robusta.model.ProjectModel;
import infobalt.robusta.model.SprintModel;
import infobalt.robusta.service.AssignmentService;
import infobalt.robusta.service.MemberService;
import infobalt.robusta.service.SprintService;

public class AssignmentController implements Serializable {

	private static final long serialVersionUID = -1389684115871062390L;

	static final Logger logger = LoggerFactory.getLogger(AssignmentController.class);

	private AssignmentSearchCriterias assCriteria = new AssignmentSearchCriterias();
	private ProjectModel projectModel;
	private AssignmentModel assignmentModel;
	private AssignmentService assignmentService;
	private MemberModel memberModel;
	private MemberService memberService;
	private SprintService sprintService;
	private SprintModel sprintModel;

	public void addNewAssignment() {
		assignmentModel.setCurrentAssignment(new Assignment());
		assignmentModel.setAssigneeId(null);
	}

	public String removeFromSprint(Assignment assignment) {
		Sprint sprint = assignment.getSprint();
		logger.debug("Assignment's(ID{}) sprint is found", assignment.getId());
		sprint.getSprintAssignments().remove(assignment);
		logger.debug("Assignment(ID{}) is removed from sprint's(ID{}) list", assignment.getId(), sprint.getId());
		assignment.setSprint(null);
		sprintService.saveSprint(sprint);
		sprintModel.setSprint(sprint);
		assignmentService.save(assignment);
		sprintService.updateAndSaveBurndownHistory(sprint);

		return "sprintView";
	}

	public String addToSprint(Assignment assignment) {
		Sprint sprint = sprintModel.getSprint();
		logger.debug("Sprint(ID{}) is found", sprint.getId());
		if (assignment == null || sprint == null) {
			logger.debug("Assignment(ID{}) is not found", assignment.getId());
			return " ";
		}
		sprint.getSprintAssignments().add(assignment);
		logger.debug("Assignment(ID{}) is added to sprint's(ID{}) list", assignment.getId(), sprint.getId());
		assignment.setSprint(sprint);
		sprintService.saveSprint(sprint);
		assignmentService.save(assignment);
		sprintService.updateAndSaveBurndownHistory(sprint);
		return "sprintView";
	}

	public void update(Assignment assignment) {
		assignmentModel.setEditedAssignment(assignment);
		assignmentModel.setCurrentAssignment(assignment);
		if (assignment.getAssignee() != null) {
			assignmentModel.setAssigneeId(assignment.getAssignee().getId());
		} else {
			assignmentModel.setAssigneeId(null);
		}
	}

	/**
	 * Saves or updates the assignment setting input values to it such as dates,
	 * assignee if any, status and other *
	 */
	public void save() throws ValidatorException {
		Assignment assignment = assignmentModel.getCurrentAssignment();
		Member assignee = null;

		if (assignmentModel.getAssigneeId() != null) {
			assignee = memberService.findMemberById(assignmentModel.getAssigneeId());
		}
		Member creator = memberModel.getLoggedMember();
		Date currentDate = new Date();
		assignment.setProject(projectModel.getManagedPro());
		if (assignment.getStatus() == null) {
			assignment.setStatus(AssignmentStatus.TODO);
			logger.debug("Assignment's(ID{}) status is set", assignment.getId());
		}
		if (assignmentModel.getEditedAssignment() != null) {
			if (assignment.getStatus().equals(AssignmentStatus.DONE)
					&& (!assignmentModel.getEditedAssignment().equals(AssignmentStatus.DONE))) {
				assignment.setDoneAuthor(assignee);
				assignment.setDoneDate(currentDate);
			}
			if (!(assignment.getStatus().equals(AssignmentStatus.DONE))
					&& assignmentModel.getEditedAssignment().equals(AssignmentStatus.DONE)) {
				assignment.setDoneAuthor(null);
				assignment.setDoneDate(null);
			}
		}
		assignmentModel.setEditedAssignment(null);

		assignment.setCreator(creator);
		logger.debug("Assignment creator is set");
		assignment.setAssignee(assignee);
		logger.debug("Assignment assignee is set");

		if (assignment.getCreationDate() == null) {
			assignment.setCreationDate(currentDate);
			logger.debug("Assignment creation date is set");
		}
		assignment.setEditedDate(currentDate);
		assignmentService.save(assignment);
		if (assignment.getSprint() != null) {
			sprintService.updateAndSaveBurndownHistory(assignment.getSprint());
		}
		assignmentModel.setCurrentAssignment(new Assignment());
	}

	public void delete(Assignment assignment) {
		assignmentService.delete(assignment);
	}

	public void cancel() {
		assignmentModel.setCurrentAssignment(null);
	}

	public List<Assignment> findAssignmentsByManagedProject() {
		return assignmentService.findAllByProject(projectModel.getManagedPro());
	}

	/**
	 * Method checks if a certain assignment belongs to any sprint.
	 * 
	 * @param assignment
	 * @return yes or no
	 */
	public boolean doesAssignmentHaveSprint(Assignment assignment) {
		if (assignment.getSprint() != null) {
			return true;
		}
		return false;
	}

	public List<Assignment> loadWorkingAssignments() {
		Member loggedWorker = memberModel.getLoggedMember();
		return assignmentService.findAssignmentsByAsignee(loggedWorker);
	}

	/**
	 * Methods redirects in a detailed view of a certain assignment in its
	 * project.
	 * 
	 * @param assignment
	 * @return page view with all assignment's data
	 */
	public String viewAssignment(Assignment assignment) {
		assignmentModel.setCurrentAssignment(assignment);
		projectModel.setManagedPro(assignment.getProject());
		return "assignmentView";
	}

	/**
	 * If any changes are made to assignment, the date of the changes is set as
	 * "edited" date.
	 */
	private void updateEditedDateAndSave() {
		Date currentDate = new Date();
		assignmentModel.getCurrentAssignment().setEditedDate(currentDate);
		assignmentService.save(assignmentModel.getCurrentAssignment());
	}

	public void setStatusToDo() {
		Assignment assToSetStatus = assignmentModel.getCurrentAssignment();
		if (assToSetStatus.getStatus().equals(AssignmentStatus.DONE)) {
			assToSetStatus.setDoneAuthor(null);
			assToSetStatus.setDoneDate(null);
		}

		assToSetStatus.setStatus(AssignmentStatus.TODO);
		logger.debug("Assignment's status changed to TODO");
		updateEditedDateAndSave();
		if (assToSetStatus.getSprint() != null) {
			sprintService.updateAndSaveBurndownHistory(assToSetStatus.getSprint());
		}
	}

	public void setStatusInProgress() {
		Assignment assToSetStatus = assignmentModel.getCurrentAssignment();
		if (assToSetStatus.getStatus().equals(AssignmentStatus.DONE)) {
			assToSetStatus.setDoneAuthor(null);
			assToSetStatus.setDoneDate(null);
		}

		assToSetStatus.setStatus(AssignmentStatus.INPROGRESS);
		logger.debug("Assignment's status changed to INRPOGRESS");
		updateEditedDateAndSave();
		if (assToSetStatus.getSprint() != null) {
			sprintService.updateAndSaveBurndownHistory(assToSetStatus.getSprint());
		}
	}

	public void setStatusDone() {
		Assignment assToSetStatus = assignmentModel.getCurrentAssignment();
		if (!assToSetStatus.getStatus().equals(AssignmentStatus.DONE)) {
			assToSetStatus.setDoneAuthor(assToSetStatus.getAssignee());
			assToSetStatus.setDoneDate(new Date());
		}
		assToSetStatus.setStatus(AssignmentStatus.DONE);
		logger.debug("Assignment's status changed to DONE");
		updateEditedDateAndSave();
		if (assToSetStatus.getSprint() != null) {
			sprintService.updateAndSaveBurndownHistory(assToSetStatus.getSprint());
		}
	}

	public void toggleSearchPanel() {
		assignmentModel.setVisible(!assignmentModel.getVisible());
	}

	/**
	 * Complete search by various criteria in all projects user is assigned to.
	 * 
	 * @return list of assignments found by entered criteria
	 */
	public List<Assignment> searchByEverything() {
		Member loggedWorker = memberModel.getLoggedMember();
		assignmentModel
				.setFoundAssignments(assignmentService.findAssignmentsByCriterias(assCriteria, loggedWorker.getId()));
		logger.debug("Assignments found by criterias set as search results");
		assignmentModel.setVisible(!assignmentModel.getVisible());
		return assignmentModel.getFoundAssignments();
	}

	/**
	 * Complete search by various criteria in a certain project.
	 * 
	 * @return list of assignments found by entered criteria
	 */
	public List<Assignment> searchByEverythingInProject() {
		Member loggedWorker = memberModel.getLoggedMember();
		Project project = projectModel.getManagedPro();
		assCriteria.setSpecificProject(project);
		assignmentModel
				.setFoundAssignments(assignmentService.findAssignmentsByCriterias(assCriteria, loggedWorker.getId()));
		assignmentModel.setVisible(!assignmentModel.getVisible());
		assCriteria.setSpecificProject(null);
		return assignmentModel.getFoundAssignments();
	}

	/**
	 * Creates set with all assignment's data shown in a grid in assignment's
	 * view in order to export all the fields to CSV file
	 * 
	 * @return Set of strings with key and value
	 */
	public Set<Entry<String, String>> createAssignmentPropertyMap() {

		Assignment assignmentToFile = assignmentModel.getCurrentAssignment();

		Map<String, String> dataToFile = new HashMap<String, String>();
		dataToFile.put("Assignment ID:", assignmentToFile.getId().toString());

src/main/webapp/pages/secure/project/ProjectMenu.xhtml
<!DOCTYPE html>
<h:html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://xmlns.jcp.org/jsf/html">
<h:head></h:head>
<h:body>

	<ui:composition>
		<h:form>
			<p:tabMenu activeIndex="#{param.i}">
				<p:menuitem outcome="Home">
					<i class="fa fa-home fa-lg"></i>
					<f:param name="i" value="0" />
				</p:menuitem>
				<p:menuitem id="addMember" value="Project Information"
					outcome="/pages/secure/project/manageProject" icon="ui-icon-search">
					<f:param name="i" value="1" />
				</p:menuitem>
				<p:menuitem id="addAssignments" value="Project Assignments"
					outcome="/pages/secure/project/assignmentList"
					icon="ui-icon-wrench">
					<f:param name="i" value="2" />
				</p:menuitem>
				<p:menuitem id="createSprint" value="Project Sprints"
					outcome="/pages/secure/project/createSprint" icon="ui-icon-star">
					<f:param name="i" value="3" />
				</p:menuitem>
				<p:menuitem id="assignmentSearch" outcome="/pages/secure/project/assignmentSearch">
					<i class="fa fa-search fa-lg"></i>
					<f:param name="i" value="4" />
				</p:menuitem>
				<p:menuitem id="help" value="Help" outcome="/pages/secure/project/help">
					<f:param name="i" value="5" />
				</p:menuitem>
				<p:menuitem icon="fa fa-sign-out" value="Logout" id="logout"
					action="#{loginMgmtBean.logout}"></p:menuitem>
			</p:tabMenu>
			<p:tooltip id="toolTipAddMember" for="addMember" trackMouse="true"
				value="Project homepage" />
			<p:tooltip id="toolTipAddAssignments" for="addAssignments"
				trackMouse="true" value="All project assignments" />
			<p:tooltip id="toolTipCreateSprint" for="createSprint"
				trackMouse="true" value="Project Sprints list" />
				<p:tooltip id="tooltipAssignmentSearch" for="assignmentSearch"
				trackMouse="true" value="Seach for assignments in this project" />
		</h:form>


	</ui:composition>
</h:body>
</h:html>

src/main/webapp/pages/secure/project/assignmentSearch.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="ProjectTemplate.xhtml">

	<ui:define name="title">
 	 	Search assignments in Project
 	 </ui:define>

	<ui:define name="content">

		<ui:include src="searchAssignmentsInProject.xhtml"></ui:include>

	</ui:define>

</ui:composition>

src/main/webapp/pages/secure/project/assignmentView.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="ProjectTemplate.xhtml">

	<ui:define name="title">
		Assignment
		
	</ui:define>

	<ui:define name="metrics">

		<h:form id="dataTable">
			<p:dataTable id="assTbl"
				value="#{assignmentController.createAssignmentPropertyMap()}"
				var="prop">
				<f:facet name="header">
					<h:outputLabel value="Assignment Information"></h:outputLabel>
				</f:facet>
				<p:column>
					<h:outputText value="#{prop.key}" />
				</p:column>
				<p:column>
					<h:outputText value="#{prop.value}" />
				</p:column>
			</p:dataTable>

<h:panelGroup layout="block" id="doneTable">

				<p:panelGrid columns="2">
					<h:outputText value="Done date" rendered="#{assignmentModel.currentAssignment.getDoneAuthor() ne null}"></h:outputText>
					<h:outputText value="#{assignmentModel.currentAssignment.doneDate}" rendered="#{assignmentModel.currentAssignment.getDoneAuthor() ne null}"/>
					<h:outputText value="Done author" rendered="#{assignmentModel.currentAssignment.getDoneAuthor() ne null}"/>
					<h:outputText
						value="#{assignmentModel.currentAssignment.doneAuthor.getFullName()}" rendered="#{assignmentModel.currentAssignment.getDoneAuthor() ne null}"/>
				</p:panelGrid>
				<br />
		</h:panelGroup>
			
<h:commandLink value="Export Project Assignments Data">
					<p:dataExporter type="csv" target="assTbl"
						fileName="robustaProjectAssignments" pageOnly="true" />
			</h:commandLink>
		</h:form>
		

		<br />
		<h:form id="buttons">
			<p:commandButton action="#{assignmentController.setStatusToDo()}"
				value="To Do" update="dataTable">
				<f:ajax render="dataTable" />
			</p:commandButton>

			<p:commandButton
				action="#{assignmentController.setStatusInProgress()}"
				value="In Progress" update="dataTable">
				<f:ajax render="dataTable" />
			</p:commandButton>

			<p:commandButton action="#{assignmentController.setStatusDone()}"
				value="Done" update="dataTable">
				<f:ajax render="dataTable" />
			</p:commandButton>
		</h:form>
		<br />



	</ui:define>

	<ui:define name="right content">
		<div id="files">
			<h3>Files</h3>
			<h:form id="filesAttached">

				<p:dataTable value="#{fileController.loadFilesByAssignment()}"
					var="file" styleClass="truncate"
					emptyMessage="No files attached yet">
					<p:column headerText="File name">
						<h:outputText id="fileName" value="#{file.fileName}"></h:outputText>
					</p:column>
					<p:column headerText="File size">
						<h:outputText id="fileSize"
							value="#{fileController.fileSizeConverted(file)}"></h:outputText>
					</p:column>
					<p:column headerText="Download">
						<p:commandButton value="Download"
							actionListener="#{fileController.download(file)}" ajax="false"
							onclick="PrimeFaces.monitorDownload(start, stop);"
							icon="ui-icon-arrowthick-1-s">
							<p:fileDownload value="#{fileController.fileModel.downloadable}" />

						</p:commandButton>
					</p:column>
				</p:dataTable>

			</h:form>


			<h:form id="filesUpload" enctype="multipart/form-data">

				<p:fileUpload dragDropSupport="true" label="Upload file"
					fileUploadListener="#{fileController.upload}"
					update="filesAttached" sizeLimit="104857600" fileLimit="5"
					invalidSizeMessage="File is too big. Maximum 100MB" />

			</h:form>

		</div>
		<div id="comments">

			<h:form id="commentList"
				rendered="#{assignmentController.assignmentModel.currentAssignment.id ne null}">

				<h3>Comments:</h3>

				<ui:repeat varStatus="status" var="comment"
					value="#{commentController.loadCommentsByAssignment()}">
					<p:panel id="c#{comment.id}">
						<f:facet name="header">
							<h:outputText value="##{comment.id}    " />
							<h:outputText value="#{comment.author.fullName}   " />
							<p:commandButton style="float:right!important" id="delete"
								icon="fa fa-trash" action="#{commentController.delete(comment)}"
								rendered="#{commentController.canDelete(comment)}"
								update="commentList">

								<p:confirm header="Delete"
									message="Are you sure you want to delete this entry?"
									icon="ui-icon-alert" />
							</p:commandButton>
							<br />
							<h:outputText value="#{comment.commentDate}">
								<f:convertDateTime pattern="yyyy-MM-dd HH:mm:ss" />
							</h:outputText>
						</f:facet>
						<h:outputText value="#{comment.commentText}" />
					</p:panel>
					<p:tooltip id="tooltipDelete" for="delete" trackMouse="true"
					value="Delete comment" />
					
				</ui:repeat>

				<p:poll partialSubmit="true" interval="10" update=":commentList"
					process="@(.commentList)"></p:poll>

				<p:confirmDialog global="true">
					<p:commandButton value="Yes" type="button"
						styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
					<p:commandButton value="No" type="button"
						styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
				</p:confirmDialog>
				
			</h:form>
			<h:form>
				<h3>You can leave a comment for this assignment:</h3>

				<p:panelGrid columns="1" id="writeComment">
					<p:message for="commentText"></p:message>
					<p:inputTextarea required="true" style="width:400px"
						requiredMessage="Comment has to have at least one symbol"
						id="commentText" value="#{commentController.model.commentText}"/>

					<p:commandButton action="#{commentController.submitComment}"
						value="Submit" update="commentList" resetValues="true"></p:commandButton>

				</p:panelGrid>
				<br />
				<br />
			</h:form>

		</div>
	</ui:define>

	<ui:define name="content">

	</ui:define>

</ui:composition>